version: "3"
#fixme  Clone openIM Server project before using docker-compose,project address：https://github.com/OpenIMSDK/Open-IM-Server.git

services:
  mysql:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./openim/mysql/data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer:4.8.1-standalone
    environment:
      TZ: Asia/Shanghai
    ports:
      - "18080:8080"
    restart: always

  mongo:
    image: mongo:4.0.27
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./openim/mongo/data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:0.54.0
    environment:
      TZ: Asia/Shanghai
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    ports:
      - "18081:8081"
    restart: always

  redis:
    image: redis:6.2.6-alpine3.15
    command: redis-server --requirepass root --save 60 1 --loglevel warning
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./openim/redis/data:/data
    sysctls:
      net.core.somaxconn: 1024
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./openim/zookeeper/data:/opt/zookeeper-3.4.6/data
    restart: always

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ./openim/kafka:/kafka
    depends_on:
      - zookeeper
    restart: always

  etcd:
    image: quay.io/coreos/etcd:v3.5.1
    command: |
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster etcd0=http://0.0.0.0:2380
      --initial-cluster-token tkn
      --initial-cluster-state new
      --log-level info
      --logger zap
      --log-outputs stderr
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./openim/etcd/data:/etcd-data
    restart: always

  open_im_server:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ./openim/Open-IM-Server/config/config.yaml:/Open-IM-Server/config/config.yaml
    ports:
      - "42233:42233"
      - "10000:10000"
      - "17778:17778"
    depends_on:
      - kafka
      - mysql
      - mongo
      - redis
      - etcd
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
    restart: always
